services:
  web:
    container_name: flask-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app # Live sync local files with container
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0"]