services:
  web:
    container_name: flask-app
    build:
      context: .
      args:
        REQ_FILE: requirements-prod.txt
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - DATABASE_HOST
      - DATABASE_PORT
      - FLASK_APP
      - FLASK_ENV
    depends_on:
      - db
    entrypoint: [ "./entrypoint.sh" ]
    volumes:
      - .:/app # Live sync local files with container
    networks:
      - backend-network

  db:
    container_name: postgres-db
    image: postgres:bullseye
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "8888:5432"
    volumes:
      # Persist PostgreSQL data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge