services:
  web:
    container_name: flask-app
    build:
      context: .
      args:
        REQ_FILE: requirements-prod.txt
    environment:
      - DATABASE_URL
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - DATABASE_HOST
      - DATABASE_PORT
      - FLASK_APP
      - FLASK_ENV
    depends_on:
      - db
    entrypoint: [ "./entrypoint.sh" ]
    volumes:
      - .:/app # Live sync local files with container
    networks:
      - backend-network

  db:
    container_name: postgres-db
    image: postgres:bullseye
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "8888:5432"
    volumes:
      # Persist PostgreSQL data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  nginx:
    container_name: nginx-proxy
    restart: unless-stopped
    image: nginx:stable-perl
    ports:
      # Expose nginx on port 80 and 443 (http / https)
      - "80:80"
      - "443:443"
    volumes:
      # Mount custom nginx config.
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    networks:
      - backend-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot 
      --force-renewal 
      --email ${CERTBOT_EMAIL} 
      -d {domain} 
      --agree-tos

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge