name: CI Pipeline with Dummy Credentials

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    # Centralised dummy environment variables
    env:
      # These dummy values are for CI testing only.
      # Repo maintainers can replace them with GitHub Secrets.
      FLASK_ENV: development
      DATABASE_USERNAME: testuser
      DATABASE_PASSWORD: testpassword
      DATABASE_NAME: testdb
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/testdb

    services:
      postgres:
        image: postgres:bullseye
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL container health check
        run: |
          echo "Checking PostgresSQL container health..."
          for i in {1..10}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' $(docker ps -q --filter expose=5432))
            echo "Health status: $STATUS"
            if [ "$STATUS" == "healthy" ]; then
              echo "PostgreSQL is healthy."
              break
            fi
            echo "Waiting for PostgreSQL to become healthy..."
            sleep 3
          done
          
          if [ "$STATUS" != "healthy" ]; then
            echo "PostgreSQL" container failed to become healthy."
            exit 1
          fi
        shell: bash

      - name: Initialize test database schema
        run: |
          PGPASSWORD=$DATABASE_PASSWORD psql -h $DATABASE_HOST -U $DATABASE_USERNAME -d $DATABASE_NAME <<EOF
          CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            email VARCHAR(255) UNIQUE NOT NULL,
            password_hash VARCHAR(255) NOT NULL
          );
          EOF

      - name: Run tests
        run: |
          pytest tests/

      - name: Build Docker image
        run: |
          docker build --build-arg REQ_FILE=requirements-prod.txt -t flask-app .